# -*- coding: utf-8 -*-
"""Diabetes Dataset Pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l2Q38h4MLdq6CEreNyZ79npe4Ed2lLYD
"""



"""
# Project: Data Quality Pipeline for Diabetes Risk Prediction

**Goal:
Clean unrealistic medical values, compare preprocessing strategies,
and measure how data cleaning affects diabetes prediction performance.**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler

df = pd.read_csv("diabetes_data.csv") # Loading the data provided

print("Dataset loaded successfully.")
print(f"Rows: {df.shape[0]}, Columns: {df.shape[1]}")
print(df.head())

df.info() # Displaying data types of each column

# Dataset has 768 rows and 9 columns of data type float.



print(df.isnull().sum()) # Display how many null values are present in each column

missing_summary = pd.DataFrame({
    "missing_count": df.isnull().sum(),
    "missing_percentage": (df.isnull().sum() / len(df)) * 100
})

print(missing_summary[missing_summary["missing_count"] > 0])

"""In this dataset, some medical measurements are recorded as 0.
For features such as Glucose, BloodPressure, SkinThickness, Insulin, and BMI,
zero is not medically realistic, so these values are treated as missing.
"""

zero_as_missing_cols = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[zero_as_missing_cols] = df[zero_as_missing_cols].replace(0, np.nan)

print("Missing values after replacing invalid 0s with NaN:")
print(df.isnull().sum())

df_before_imputation = df.copy()

"""Glucose - Median

Shows a right-skewed distribution with invalid zero values.
Using the mean would distort the data, so median imputation provides
a more stable and realistic central value.


BloodPressure – Median

* Contains 0 values which are not realistic
* Distribution may be affected by these values
* Median is more reliable

SkinThickness – Median

* Large number of 0 values indicating missing data
* Right-skewed distribution
* Median handles skew better

Insulin – Median

* Highly right-skewed with extreme outliers
* Many 0 values treated as missing
* Mean would be distorted, median is safer

BMI – Median

* Contains 0 values which are invalid
* Slightly skewed distribution
* Median is more appropriate

"""

df.hist(figsize=(12, 10), bins=30)
plt.show()

df.hist(figsize=(12, 10), bins=30) # Distribution before imputation
plt.title("Distribution Before Imputation (After Replacing Invalid 0s with NaN)")
plt.show()

# NaN_Cols contains all the columns with missing values.
# These need median imputation.

median_cols = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']

df[median_cols] = df[median_cols].fillna(df[median_cols].median())

comparison_summary = pd.DataFrame({
    "missing_values_before": df_before_imputation[median_cols].isnull().sum(),
    "missing_percentage_before": (df_before_imputation[median_cols].isnull().sum() / len(df)) * 100,
    "median_used_for_imputation": df_before_imputation[median_cols].median(),
    "mean_before_imputation": df_before_imputation[median_cols].mean(),
    "mean_after_imputation": df[median_cols].mean()
})

comparison_summary = comparison_summary.round(2)

print("Before vs After Imputation Summary:")
print(comparison_summary)

df['Outcome'] = df['Outcome'].fillna(df['Outcome'].mode()[0])

print("Missing values after imputation:")
print(df.isnull().sum())

df.info()

"""We now visualise imputation by comparing
data before and after imputation.
"""

imputed_cols = median_cols + ['Outcome']

for col in imputed_cols:
    plt.figure(figsize=(10, 4))

    plt.subplot(1, 2, 1)
    sns.histplot(df_before_imputation[col], kde=True, bins=30)
    plt.title(f"{col} - Before Imputation")

    plt.subplot(1, 2, 2)
    sns.histplot(df[col], kde=True, bins=30)
    plt.title(f"{col} - After Imputation")

    plt.tight_layout()
    plt.show()

sns.heatmap(df.corr(), annot=True, cmap="coolwarm")
plt.title("Feature Correlation Heatmap")
plt.show()

features = df.drop(columns=['Outcome'])

standard_scaler = StandardScaler() #standard scaler
minmax_scaler = MinMaxScaler()
robust_scaler = RobustScaler()

standard_scaled_df = pd.DataFrame(
    standard_scaler.fit_transform(features),
    columns=features.columns
)

minmax_scaled_df = pd.DataFrame(
    minmax_scaler.fit_transform(features),
    columns=features.columns
) # minmax scaler

robust_scaled_df = pd.DataFrame(
    robust_scaler.fit_transform(features),
    columns=features.columns
) #robust scaler

standard_scaled_df['Outcome'] = df['Outcome'].values
minmax_scaled_df['Outcome'] = df['Outcome'].values
robust_scaled_df['Outcome'] = df['Outcome'].values

scaled_dfs = {
    "Standard Scaled": standard_scaled_df,
    "MinMax Scaled": minmax_scaled_df,
    "Robust Scaled": robust_scaled_df
}

for scaler_name, scaled_df in scaled_dfs.items():
    for col in features.columns:
        plt.figure(figsize=(10, 4))

        plt.subplot(1, 2, 1)
        sns.histplot(features[col], kde=True, bins=30)
        plt.title(f"{col} - Original")

        plt.subplot(1, 2, 2)
        sns.histplot(scaled_df[col], kde=True, bins=30)
        plt.title(f"{col} - {scaler_name}")

        plt.tight_layout()
        plt.show()

"""
**Key Observations**

- Median imputation preserved the overall distribution shape across features
- Insulin remained highly skewed even after cleaning, indicating that extreme values persist and may influence model performance
- Missing values were effectively handled without introducing artificial bias
- The dataset is now more stable for downstream modeling
"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

def evaluate_model(data, label):
    X = data.drop(columns=["Outcome"])
    y = data["Outcome"]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    model = LogisticRegression(max_iter=1000)
    model.fit(X_train, y_train)

    preds = model.predict(X_test)

    return {
        "dataset": label,
        "accuracy": accuracy_score(y_test, preds),
        "precision": precision_score(y_test, preds),
        "recall": recall_score(y_test, preds),
        "f1_score": f1_score(y_test, preds)
    }

results = pd.DataFrame([
    evaluate_model(standard_scaled_df, "Standard Scaled"),
    evaluate_model(minmax_scaled_df, "MinMax Scaled"),
    evaluate_model(robust_scaled_df, "Robust Scaled")
])

print(results)

best_model = results.loc[results["f1_score"].idxmax()]

print("\nBest Performing Scaling Method:")
print(f"{best_model['dataset']} with F1 Score: {round(best_model['f1_score'], 3)}")

results.set_index("dataset")[["accuracy", "precision", "recall", "f1_score"]].plot(
    kind="bar", figsize=(10, 6)
)

plt.title("Model Performance Across Scaling Techniques")
plt.ylabel("Score")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

standard_scaled_df.to_csv("diabetes_standard_scaled.csv", index=False)
minmax_scaled_df.to_csv("diabetes_minmax_scaled.csv", index=False)
robust_scaled_df.to_csv("diabetes_robust_scaled.csv", index=False)
results.to_csv("model_performance_results.csv", index=False)

print("Processed datasets and model results saved successfully.")